sources:
  - name: src
    description: CRM sales data
    tables:
      - name: deal_pipeline_stages
        description: "Deal stage source data"
        columns:
          - name: DEAL_ID
            data_type: integer
            tests:
              - not_null
              - unique
          - name: STAGE_CREATED_AT
            data_type: timestamp
            tests:
              - not_null
          - name: PIPELINE_ID
            data_type: varchar
            tests:
              - not_null
          - name: PIPELINE_NAME
            data_type: varchar
            tests:
              - not_null
          - name: DEAL_STAGE_ID
            data_type: varchar
            tests:
              - not_null
          - name: STAGE_NAME
            data_type: varchar
            tests:
              - not_null
          - name: STAGE_DISPLAY_ORDER
            data_type: integer
            tests:
              - not_null
      - name: deals
        description: "Deal source data"
        columns:
          - name: DEAL_ID
            data_type: integer
            tests:
              - not_null
          - name: PIPELINE_ID
            data_type: varchar
            tests:
              - not_null
          - name: PIPELINE_NAME
            data_type: varchar
            tests:
              - not_null
          - name: STAGE_NAME
            data_type: varchar
            tests:
              - not_null
          - name: AMOUNT_IN_HOME_CURRENCY
            data_type: float
          - name: CREATED_AT
            data_type: timestamp
            tests:
              - not_null
          - name: CLOSE_DATE
            data_type: timestamp
            tests:
              - not_null
          - name: DEAL_SOURCE_TYPE
            data_type: varchar
            tests:
              - not_null